#!/usr/bin/env python

Import('env')

env_module = env.Clone()
env_module.Prepend(CPPPATH=["thirdparty/trezor-crypto"])
env_module.Append(CDEFINES=["USE_KECCAK", "USE_ETHEREUM"])

env_thirdparty = env_module.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, "thirdparty/trezor-crypto/*.c")

env_module.add_source_files(env.modules_sources, "*.cpp")

# scons custom_modules=../modules platform=osx arch=arm64 --jobs=$(sysctl -n hw.logicalcpu)